import { describe, it } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const MIGRATIONS_DIR = path.resolve(fileURLToPath(import.meta.url), "..", "..", "..", "server", "migrations");

const MIGRATION_FILE = /^\d{4}-.+\.js$/;

const onDisk = fs.readdirSync(MIGRATIONS_DIR).filter((file) => MIGRATION_FILE.test(file)).sort();

const registry = (await import("../../server/migrations/index.js")).default;

/**
 * server/migrations/index.js is generated by scripts/generate-migrations.js and
 * is gitignored, so it is whatever the last build left behind. A migration that
 * was written but never regenerated into it is simply never run - and every
 * other test still passes, because the suite boots against a registry that does
 * not know the new file exists.
 *
 * This is the only thing that notices, so it deliberately reads the directory
 * rather than trusting the registry.
 */
describe("the migration registry", () => {
    it("finds migrations on disk to check", () => {
        assert.ok(onDisk.length > 0, "no migration files matched the naming convention");
    });

    it("registers every migration that exists", () => {
        const registered = registry.map((migration) => migration.name);

        for (const file of onDisk)
            assert.ok(registered.includes(file),
                `${file} is not in the generated registry - run "npm run generate-migrations"`);
    });

    it("registers nothing that does not exist", () => {
        for (const migration of registry)
            assert.ok(onDisk.includes(migration.name), `${migration.name} is registered but not on disk`);
    });

    // The runner executes them in array order and records each by name, so a
    // registry out of order would apply a later migration against a schema an
    // earlier one had not built yet.
    it("keeps them in the order their names sort in", () => {
        assert.deepEqual(registry.map((migration) => migration.name), onDisk);
    });

    it("gives every migration something to run", () => {
        for (const migration of registry)
            assert.equal(typeof migration.up, "function", `${migration.name} exports no up()`);
    });
});
